FROM postgres:16
RUN printf '# TYPE  DATABASE        USER            ADDRESS                 METHOD\nlocal   all             all                                     trust\nhost    all             all             127.0.0.1/32            md5\nhost    all             all             ::1/128                 md5\nhost    all             all             0.0.0.0/0               md5\nhost    replication     replicator      0.0.0.0/0               md5\n' \
    > /etc/postgresql/pg_hba.conf
